spring.application.name=fastomni

spring.application.name=kafka-mongo-consumer

# =========================
# VIRTUAL THREADS
# =========================
# Opcional. Boot suporta isso em Java 21+.
spring.threads.virtual.enabled=true

# =========================
# KAFKA
# =========================
spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=orders-group
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.value.default.type=com.example.fastomni.kafka.OrderEvent
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.fastomni.kafka.kafka

# tuning Kafka
spring.kafka.consumer.max-poll-records=1000
spring.kafka.consumer.properties.fetch.min.bytes=1048576
spring.kafka.consumer.properties.fetch.max.wait.ms=250
spring.kafka.consumer.properties.max.partition.fetch.bytes=5242880
spring.kafka.consumer.properties.max.poll.interval.ms=300000
spring.kafka.consumer.properties.session.timeout.ms=30000
spring.kafka.consumer.properties.heartbeat.interval.ms=10000
spring.kafka.listener.type=batch
spring.kafka.listener.ack-mode=manual
spring.kafka.listener.concurrency=6
spring.kafka.listener.poll-timeout=1500


################## config para modelo de controle dos erros ao processar LOTE
## aceitando de forma parcial o LOTE do LISTENER mostrando os que deram  erro
# O ErrorHandlingDeserializer encapsula o erro e disponibiliza a exceção em headers,
# em vez de explodir o poll inteiro. Mas, em batch listener, a checagem desses
# headers continua sendo responsabilidade do seu código

#spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
#spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
#spring.kafka.consumer.properties.spring.json.value.default.type=com.example.fastomni.kafka.OrderEvent
#spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.fastomni.kafka.kafka

# =========================
# MONGO
# =========================
spring.data.mongodb.uri=mongodb://localhost:27017/orderdb

# app mongo tuning
app.mongo.database=orderdb
app.mongo.collection=orders
app.mongo.max-pool-size=120
app.mongo.min-pool-size=20
app.mongo.max-connecting=12
app.mongo.connect-timeout-ms=3000
app.mongo.read-timeout-ms=15000
app.mongo.server-selection-timeout-ms=3000

# =========================
# APP BATCHING
# =========================
app.insert.batch-size=1000
app.insert.parallelism=8